// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

/*
Package repo is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	ProtoAnimalQuestion
	ProtoAnimalAnswer
	ProtoError
	ProtoAnimalList
*/
package repo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoAnimalQuestion struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *ProtoAnimalQuestion) Reset()                    { *m = ProtoAnimalQuestion{} }
func (m *ProtoAnimalQuestion) String() string            { return proto.CompactTextString(m) }
func (*ProtoAnimalQuestion) ProtoMessage()               {}
func (*ProtoAnimalQuestion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoAnimalQuestion) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProtoAnimalQuestion) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ProtoAnimalAnswer struct {
	Id      int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Content bool  `protobuf:"varint,2,opt,name=content" json:"content,omitempty"`
}

func (m *ProtoAnimalAnswer) Reset()                    { *m = ProtoAnimalAnswer{} }
func (m *ProtoAnimalAnswer) String() string            { return proto.CompactTextString(m) }
func (*ProtoAnimalAnswer) ProtoMessage()               {}
func (*ProtoAnimalAnswer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoAnimalAnswer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProtoAnimalAnswer) GetContent() bool {
	if m != nil {
		return m.Content
	}
	return false
}

type ProtoError struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *ProtoError) Reset()                    { *m = ProtoError{} }
func (m *ProtoError) String() string            { return proto.CompactTextString(m) }
func (*ProtoError) ProtoMessage()               {}
func (*ProtoError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProtoError) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ProtoAnimalList struct {
	Content []string `protobuf:"bytes,1,rep,name=content" json:"content,omitempty"`
}

func (m *ProtoAnimalList) Reset()                    { *m = ProtoAnimalList{} }
func (m *ProtoAnimalList) String() string            { return proto.CompactTextString(m) }
func (*ProtoAnimalList) ProtoMessage()               {}
func (*ProtoAnimalList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtoAnimalList) GetContent() []string {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoAnimalQuestion)(nil), "repo.ProtoAnimalQuestion")
	proto.RegisterType((*ProtoAnimalAnswer)(nil), "repo.ProtoAnimalAnswer")
	proto.RegisterType((*ProtoError)(nil), "repo.ProtoError")
	proto.RegisterType((*ProtoAnimalList)(nil), "repo.ProtoAnimalList")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x4a, 0x2d, 0xc8, 0x57, 0xb2, 0xe7, 0x12,
	0x0e, 0x00, 0x71, 0x1d, 0xf3, 0x32, 0x73, 0x13, 0x73, 0x02, 0x4b, 0x53, 0x8b, 0x4b, 0x32, 0xf3,
	0xf3, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32,
	0x53, 0x84, 0x24, 0xb8, 0xd8, 0x93, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x98, 0x14, 0x18,
	0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x5b, 0x2e, 0x41, 0x24, 0x03, 0x1c, 0xf3, 0x8a, 0xcb, 0x53,
	0x8b, 0x08, 0x69, 0xe7, 0x40, 0x68, 0x57, 0xe3, 0xe2, 0x02, 0x6b, 0x77, 0x2d, 0x2a, 0xca, 0x2f,
	0x42, 0x56, 0xc7, 0x88, 0x6a, 0x8d, 0x36, 0x17, 0x3f, 0x92, 0x35, 0x3e, 0x99, 0xc5, 0x25, 0xa8,
	0x8a, 0x99, 0x91, 0x14, 0x27, 0xb1, 0x81, 0x7d, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0xb3, 0xe9, 0x3f, 0xef, 0x00, 0x00, 0x00,
}
